name: force_directed_graphview
description: A highly customizable library for displaying force-directed graphs in Flutter.
version: 0.5.0

homepage: https://github.com/cupofme/force_directed_graphview
repository: https://github.com/cupofme/force_directed_graphview
issue_tracker: https://github.com/cupofme/force_directed_graphview/issues

topics:
  - graph
  - graphview
  - force-directed-graph

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.9.1
  vector_math: ^2.1.4
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0
